name: gravity-case-studies
channels:
    - conda-forge
    - defaults
dependencies:
    - asn1crypto=0.24.0=py27_0
    - backports=1.0=py27_1
    - backports.functools_lru_cache=1.5=py27_0
    - backports.shutil_get_terminal_size=1.0.0=py_3
    - backports_abc=0.5=py27_0
    - basemap=1.1.0=py27_4
    - basemap-data-hires=1.1.0=0
    - blas=1.1=openblas
    - bleach=2.1.3=py_0
    - bokeh=0.12.15=py27_0
    - bottleneck=1.2.1=py27_1
    - ca-certificates=2018.1.18=0
    - cartopy=0.16.0=py27_0
    - certifi=2018.1.18=py27_0
    - cffi=1.11.5=py27_0
    - chardet=3.0.4=py27_0
    - click=6.7=py_1
    - cloudpickle=0.5.2=py_0
    - cmocean=1.1=py_0
    - configparser=3.5.0=py27_0
    - cryptography=2.2.1=py27_0
    - curl=7.59.0=1
    - cycler=0.10.0=py27_0
    - cyordereddict=1.0.0=py27_1
    - cytoolz=0.9.0.1=py27_0
    - dask=0.17.2=py_0
    - dask-core=0.17.2=py_0
    - dbus=1.10.22=0
    - decorator=4.2.1=py27_0
    - distributed=1.21.6=py27_0
    - entrypoints=0.2.3=py27_1
    - enum34=1.1.6=py27_1
    - expat=2.2.5=0
    - fatiando=0.5=np111py27_1
    - fontconfig=2.12.6=0
    - freetype=2.8.1=0
    - funcsigs=1.0.2=py_2
    - functools32=3.2.3.2=py27_2
    - future=0.16.0=py27_0
    - futures=3.2.0=py27_0
    - geos=3.6.2=1
    - gettext=0.19.8.1=0
    - glib=2.55.0=0
    - gmp=6.1.2=0
    - gst-plugins-base=1.8.0=0
    - gstreamer=1.8.0=1
    - h5netcdf=0.5.0=py_0
    - h5py=2.7.1=py27_3
    - hdf4=4.2.13=0
    - hdf5=1.10.1=2
    - heapdict=1.0.0=py27_0
    - html5lib=1.0.1=py_0
    - icu=58.2=0
    - idna=2.6=py27_1
    - ipaddress=1.0.18=py27_0
    - ipykernel=4.8.2=py27_0
    - ipython=5.6.0=py27_0
    - ipython_genutils=0.2.0=py27_0
    - ipywidgets=7.2.0=py27_0
    - jinja2=2.10=py27_0
    - jpeg=9b=2
    - jsonschema=2.6.0=py27_1
    - jupyter=1.0.0=py_1
    - jupyter_client=5.2.3=py27_0
    - jupyter_console=5.2.0=py27_0
    - jupyter_core=4.4.0=py_0
    - kiwisolver=1.0.1=py27_1
    - krb5=1.14.6=0
    - libffi=3.2.1=3
    - libiconv=1.15=0
    - libnetcdf=4.5.0=3
    - libpng=1.6.34=0
    - libsodium=1.0.16=0
    - libssh2=1.8.0=2
    - libtiff=4.0.9=0
    - libxcb=1.13=0
    - libxml2=2.9.8=0
    - libxslt=1.1.32=0
    - locket=0.2.0=py27_1
    - lxml=4.2.1=py27_0
    - markupsafe=1.0=py27_0
    - matplotlib=2.2.2=py27_1
    - mistune=0.8.3=py_0
    - msgpack-python=0.5.6=py27_0
    - nbconvert=5.3.1=py_1
    - nbformat=4.4.0=py27_0
    - ncurses=5.9=10
    - netcdf4=1.3.1=py27_2
    - notebook=5.4.1=py27_0
    - numpy=1.11.3=py27_blas_openblas_203
    - olefile=0.45.1=py27_0
    - openblas=0.2.20=7
    - openssl=1.0.2n=0
    - owslib=0.16.0=py_0
    - packaging=17.1=py_0
    - pandas=0.22.0=py27_0
    - pandoc=2.1.3=0
    - pandocfilters=1.4.1=py27_0
    - partd=0.3.8=py27_0
    - pathlib2=2.3.0=py27_0
    - pcre=8.41=1
    - pexpect=4.4.0=py27_0
    - pickleshare=0.7.4=py27_0
    - pillow=5.1.0=py27_0
    - pip=9.0.3=py27_0
    - proj4=4.9.3=5
    - prompt_toolkit=1.0.15=py27_0
    - psutil=5.4.3=py27_0
    - ptyprocess=0.5.2=py27_0
    - pycparser=2.18=py27_0
    - pyepsg=0.3.2=py27_0
    - pygments=2.2.0=py27_0
    - pyopenssl=17.5.0=py27_1
    - pyparsing=2.2.0=py27_0
    - pyproj=1.9.5.1=py27_0
    - pyqt=5.6.0=py27_4
    - pyshp=1.2.12=py_0
    - pysocks=1.6.8=py27_1
    - python=2.7.14=5
    - python-dateutil=2.7.2=py_0
    - pytz=2018.3=py_0
    - pyyaml=3.12=py27_1
    - pyzmq=17.0.0=py27_4
    - qt=5.6.2=7
    - qtconsole=4.3.1=py27_0
    - readline=7.0=0
    - requests=2.18.4=py27_1
    - scandir=1.7=py27_0
    - scipy=1.0.1=py27_blas_openblas_200
    - send2trash=1.5.0=py_0
    - setuptools=39.0.1=py27_0
    - shapely=1.6.4=py27_0
    - simplegeneric=0.8.1=py27_0
    - singledispatch=3.4.0.3=py27_0
    - sip=4.18=py27_1
    - six=1.11.0=py27_1
    - sortedcontainers=1.5.9=py27_0
    - sqlite=3.20.1=2
    - subprocess32=3.2.7=py27_0
    - tblib=1.3.2=py27_0
    - terminado=0.8.1=py27_0
    - testpath=0.3.1=py27_0
    - tk=8.6.7=0
    - toolz=0.9.0=py_0
    - tornado=5.0.2=py27_0
    - traitlets=4.3.2=py27_0
    - urllib3=1.22=py27_0
    - wcwidth=0.1.7=py27_0
    - webencodings=0.5=py27_0
    - wheel=0.31.0=py27_0
    - widgetsnbextension=3.2.0=py27_0
    - xarray=0.10.2=py27_0
    - xorg-libxau=1.0.8=3
    - xorg-libxdmcp=1.1.2=3
    - xz=5.2.3=0
    - yaml=0.1.7=0
    - zeromq=4.2.5=1
    - zict=0.1.3=py_0
    - zlib=1.2.11=0
    - libgcc-ng=7.2.0=hdf63c60_3
    - libgfortran=3.0.0=1
    - libstdcxx-ng=7.2.0=hdf63c60_3
    - llvmlite=0.22.0=py27hdbca893_0
    - numba=0.37.0=np111py27h2eedcfd_0
    - pip:
        - backports-abc==0.5
        - backports.functools-lru-cache==1.5
        - backports.shutil-get-terminal-size==1.0.0
        - ipython-genutils==0.2.0
        - jupyter-client==5.2.3
        - jupyter-console==5.2.0
        - jupyter-core==4.4.0
        - prompt-toolkit==1.0.15
